### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by Overbryd** [codebrawl/codebrawl#13] opened 2011-07-01 22:00 UTC
The build is broken, but it wasn't me™

```
Build Update for codebrawl/codebrawl
--------------------------------------------------------

Build : #33

Duration : 2 minutes and 41 seconds
Commit : 37136247 (open_contests)
Author : Overbryd
Message : Featured contests now appear on top, no visual distinction yet [Closes #9]

Status : Failed

View the changeset : https://github.com/codebrawl/codebrawl/compare/2897ab6...3713624

View the full build log and details : http://travis-ci.org/codebrawl/codebrawl/builds/36320
```

**Comment by jeffkreeftmeijer** [comment] 2011-07-04 09:45
The problem is that it doesn't have a javascript Runtime (Codebrawl uses Node.js, which is not installed on Travis). We need to add a "ci"-env for Travis that uses therubyracer or something like that. I'll assign this one to myself and I'll post updates here.

Thanks for reporting, Lukas. :)

**Comment by jeffkreeftmeijer** [comment] 2011-07-04 17:23
We're having some trouble with `Contest#(starting|voting|finishing)_on`. They work correctly on the production server (UTC), but not on my box, or on Travis (both CEST). I'm out of ideas. @overbryd does it work on your machine? :)

**Comment by Overbryd** [comment] 2011-07-05 07:24
Maybe you could use the timezine aware Time.current?

**Comment by jeffkreeftmeijer** [comment] 2011-07-05 08:11
I don't think it's that, it's going wrong in `closing_on.to_time.utc + 14.hours`, which returns 12:00 instead of 14:00 (where `closing_on` is a date).

**Comment by jeffkreeftmeijer** [comment] 2011-07-09 08:48
The CI is passing now (http://travis-ci.org/#!/codebrawl/codebrawl). Thanks for reporting! :)

**Closed as completed by jeffkreeftmeijer** 2011-07-09 08:48 UTC

**Comment by Overbryd** [comment] 2011-07-09 12:36
Great job :)
